### ISSUE TITLE
Missing dependency after upgrade to v0.4.0

### ISSUE THREAD

**Issue by phutchins** [Storj/metadisk-client#12]
After upgrading to storj-bridge-client 0.4.0, and also after a clean install of 0.4.0, I'm getting the following error for a missing dependency.

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'elliptic'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/philip/.nvm/versions/node/v4.4.3/lib/node_modules/storj-bridge-client/lib/keypair.js:5:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

I've manually installed the elliptic module and it seems to resolve the issue.

**Comment by phutchins** [comment]
Submitted a PR with the fix for this here: https://github.com/Storj/bridge-client-javascript/pull/13
